// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvrG7UNGtTGPAx7WGUH5c7FG4RZIqyLM',
    appId: '1:165550640430:web:bc8e22df19b97764de7ebf',
    messagingSenderId: '165550640430',
    projectId: 'message-board-app-4ec63',
    authDomain: 'message-board-app-4ec63.firebaseapp.com',
    storageBucket: 'message-board-app-4ec63.firebasestorage.app',
    measurementId: 'G-TB9WL6JL54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCheX485xxQ-G6krQWCO48pz1plJURYs4c',
    appId: '1:165550640430:android:d5b814e08bc91959de7ebf',
    messagingSenderId: '165550640430',
    projectId: 'message-board-app-4ec63',
    storageBucket: 'message-board-app-4ec63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAREcBWPigEstqWytFcvXBzOzmChttMwoQ',
    appId: '1:165550640430:ios:781b7a41ce1ce54cde7ebf',
    messagingSenderId: '165550640430',
    projectId: 'message-board-app-4ec63',
    storageBucket: 'message-board-app-4ec63.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAREcBWPigEstqWytFcvXBzOzmChttMwoQ',
    appId: '1:165550640430:ios:781b7a41ce1ce54cde7ebf',
    messagingSenderId: '165550640430',
    projectId: 'message-board-app-4ec63',
    storageBucket: 'message-board-app-4ec63.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGvrG7UNGtTGPAx7WGUH5c7FG4RZIqyLM',
    appId: '1:165550640430:web:09cc9c0145a8c845de7ebf',
    messagingSenderId: '165550640430',
    projectId: 'message-board-app-4ec63',
    authDomain: 'message-board-app-4ec63.firebaseapp.com',
    storageBucket: 'message-board-app-4ec63.firebasestorage.app',
    measurementId: 'G-4KHL0W2RL0',
  );
}
